name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
        # 2.2081 геод фикс
          sdk: v5.7.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fenixgdps-thumbnails-mod
          path: build/*.geode
# блять cpp это говнище ебаное
